package com.hamyareman.ir.ui.wellness

import com.hamyareman.ir.ui.wellness.WellnessMove.Category

/**
 * پرامپت ۰۲ — کاتالوگ کامل حرکات یوگا/ورزش/تنفس/یادگیری.
 *
 * نکته‌ها:
 *  - ۱۵ یوگا، ۱۵ ورزش، ۸ تنفس، ۵ یادگیری = ۴۳ حرکت (مطابق معیارهای پذیرش پرامپت ۰۲).
 *  - تصاویر ۱۵ یوگا و ۱۵ ورزش بر اساس نام حرکت داخل APK هستند؛ تنفس/یادگیری
 *    تا زمان جایگزینی منبع اختصاصی از مسیر رسانه‌ای موجود استفاده می‌کنند.
 *  - `referenceImagePromptTemplate` برای قابلیت آینده‌ی «تولید دوباره با چهره‌ی کاربر» نگه داشته شده.
 *  - `audioCueId` به فایل صوتی TTS فارسی اشاره می‌کند که در همان باکت آپلود می‌شود.
 */
object WellnessCatalog {

    private const val IMG_BASE = "https://fra.cloud.appwrite.io/v1/storage/buckets/wellness-media/files/"
    private const val IMG_VIEW = "/view?project=6a9d59e3002751cc3ea8"

    private fun imageUrl(filename: String): String = "$IMG_BASE$filename$IMG_VIEW"
    private fun embeddedCover(id: String): String = "file:///android_asset/practice-covers/$id.jpg"

    // ---------------- یوگا (15) ----------------

    val yoga: List<WellnessMove> = listOf(
        WellnessMove(
            slug = "yoga-balasana",
            category = Category.YOGA,
            titleFa = "کودک (Balasana)",
            level = 1,
            durationSec = 60,
            instructionsFa = "روی پاشنه‌ها بنشین، زانوها کنار هم. نفس را بیرون بده و تنه را به جلو خم کن تا پیشانی روی تشک بیاید. دست‌ها را به جلو بکش.",
            audioCueId = "cue-yoga-balasana-start.mp3|cue-yoga-balasana-mid.mp3|cue-yoga-balasana-end.mp3",
            referenceImageUrl = embeddedCover("yga-01"),
            referenceImagePromptTemplate = "یک تصویر آموزشی ساده و واضح از حالت بدنی کودک (Balasana)، با چهره‌ای شبیه به تصویر پیوست‌شده (فقط شباهت چهره، نه کپی دقیق)، در پوشش ورزشی محجبه و مناسب، پس‌زمینه‌ی ساده و روشن، زاویه‌ی دید کامل بدن، سبک illustration آموزشی، بدون متن روی تصویر.",
            orderIndex = 1,
            tags = listOf("آرامش‌بخش", "کشش کمر"),
        ),
        WellnessMove(
            slug = "yoga-cat-cow",
            category = Category.YOGA,
            titleFa = "گربه-گاو",
            level = 2,
            durationSec = 60,
            instructionsFa = "روی چهار دست و پا. با دم کمر را به سمت پایین قوس بده و سر را بالا ببر (گاو). با بازدم کمر را گرد کن و سر را پایین ببر (گربه). ۸ بار تکرار.",
            audioCueId = "cue-yoga-cat-cow-start.mp3|cue-yoga-cat-cow-mid.mp3|cue-yoga-cat-cow-end.mp3",
            referenceImageUrl = embeddedCover("yga-02"),
            referenceImagePromptTemplate = "تصویر آموزشی از حرکت گربه-گاو (Cat-Cow) با چهره‌ی مرجع، نمای پهلو، پوشش ورزشی، بدون متن.",
            orderIndex = 2,
        ),
        WellnessMove(
            slug = "yoga-downward-dog",
            category = Category.YOGA,
            titleFa = "سگ رو به پایین",
            level = 4,
            durationSec = 45,
            instructionsFa = "روی چهار دست و پا، انگشتان را باز کن. با بازدم لگن را بالا ببر تا بدن V شکل شود. پاشنه‌ها را به سمت زمین هل بده.",
            audioCueId = "cue-yoga-downward-dog-start.mp3|cue-yoga-downward-dog-mid.mp3|cue-yoga-downward-dog-end.mp3",
            referenceImageUrl = embeddedCover("yga-03"),
            referenceImagePromptTemplate = "تصویر آموزشی از سگ رو به پایین (Downward Dog) با چهره‌ی مرجع، نمای پهلو، پوشش ورزشی، بدون متن.",
            orderIndex = 3,
            tags = listOf("کشش همسترینگ", "تقویت شانه"),
        ),
        WellnessMove(
            slug = "yoga-cobra",
            category = Category.YOGA,
            titleFa = "کبرا",
            level = 3,
            durationSec = 30,
            instructionsFa = "روی شکم دراز بکش، کف دست‌ها زیر شانه‌ها. با دم بالاتنه را بالا ببر، آرنج‌ها کنار بدن، شانه‌ها از گوش دور.",
            audioCueId = "cue-yoga-cobra-start.mp3|cue-yoga-cobra-mid.mp3|cue-yoga-cobra-end.mp3",
            referenceImageUrl = embeddedCover("yga-04"),
            referenceImagePromptTemplate = "تصویر آموزشی از حرکت کبرا (Cobra) با چهره‌ی مرجع، نمای سه‌ربع، پوشش ورزشی، بدون متن.",
            orderIndex = 4,
            tags = listOf("تقویت کمر"),
        ),
        WellnessMove(
            slug = "yoga-warrior-1",
            category = Category.YOGA,
            titleFa = "جنگجو ۱",
            level = 4,
            durationSec = 30,
            instructionsFa = "پای جلو خم با زانوی ۹۰ درجه، پای عقب صاف و ۴۵ درجه چرخیده. دست‌ها بالا، کف دست‌ها رو به هم. لگن رو به جلو.",
            audioCueId = "cue-yoga-warrior-1-start.mp3|cue-yoga-warrior-1-mid.mp3|cue-yoga-warrior-1-end.mp3",
            referenceImageUrl = embeddedCover("yga-05"),
            referenceImagePromptTemplate = "تصویر آموزشی از جنگجو ۱ (Warrior I) با چهره‌ی مرجع، نمای جلو، پوشش ورزشی، بدون متن.",
            orderIndex = 5,
        ),
        WellnessMove(
            slug = "yoga-warrior-2",
            category = Category.YOGA,
            titleFa = "جنگجو ۲",
            level = 4,
            durationSec = 30,
            instructionsFa = "پای جلو خم ۹۰ درجه، پای عقب صاف. دست‌ها افقی موازی زمین، نگاه روی انگشتان دست جلو.",
            audioCueId = "cue-yoga-warrior-2-start.mp3|cue-yoga-warrior-2-mid.mp3|cue-yoga-warrior-2-end.mp3",
            referenceImageUrl = embeddedCover("yga-06"),
            referenceImagePromptTemplate = "تصویر آموزشی از جنگجو ۲ (Warrior II) با چهره‌ی مرجع، نمای پهلو، پوشش ورزشی، بدون متن.",
            orderIndex = 6,
        ),
        WellnessMove(
            slug = "yoga-tree",
            category = Category.YOGA,
            titleFa = "درخت",
            level = 5,
            durationSec = 30,
            instructionsFa = "روی پای چپ بایست، کف پای راست روی ران داخلی چپ (بالای زانو). دست‌ها بالا، کف دست‌ها کنار هم. تمرکز روی نقطه‌ای ثابت.",
            audioCueId = "cue-yoga-tree-start.mp3|cue-yoga-tree-mid.mp3|cue-yoga-tree-end.mp3",
            referenceImageUrl = embeddedCover("yga-07"),
            referenceImagePromptTemplate = "تصویر آموزشی از درخت (Tree Pose) با چهره‌ی مرجع، نمای جلو، پوشش ورزشی، بدون متن.",
            orderIndex = 7,
            tags = listOf("تعادل"),
        ),
        WellnessMove(
            slug = "yoga-bridge",
            category = Category.YOGA,
            titleFa = "پل",
            level = 3,
            durationSec = 30,
            instructionsFa = "به پشت دراز بکش، زانوها خم، کف پا روی زمین. لگن را بالا ببر، شانه‌ها و کف پا تکیه‌گاه. چانه کمی به سمت سینه.",
            audioCueId = "cue-yoga-bridge-start.mp3|cue-yoga-bridge-mid.mp3|cue-yoga-bridge-end.mp3",
            referenceImageUrl = embeddedCover("yga-08"),
            referenceImagePromptTemplate = "تصویر آموزشی از پل (Bridge Pose) با چهره‌ی مرجع، نمای پهلو، پوشش ورزشی، بدون متن.",
            orderIndex = 8,
            tags = listOf("تقویت باسن", "کشش شکم"),
        ),
        WellnessMove(
            slug = "yoga-spinal-twist",
            category = Category.YOGA,
            titleFa = "پیچش ستون فقرات",
            level = 3,
            durationSec = 45,
            instructionsFa = "بنشین، پای چپ صاف، زانوی راست خم و از روی پای چپ رد کن. دست راست پشت بدن، دست چپ زانوی راست را بغل کند. به راست بچرخ.",
            audioCueId = "cue-yoga-spinal-twist-start.mp3|cue-yoga-spinal-twist-mid.mp3|cue-yoga-spinal-twist-end.mp3",
            referenceImageUrl = embeddedCover("yga-09"),
            referenceImagePromptTemplate = "تصویر آموزشی از پیچش ستون فقرات (Seated Spinal Twist) با چهره‌ی مرجع، نمای سه‌ربع، پوشش ورزشی، بدون متن.",
            orderIndex = 9,
        ),
        WellnessMove(
            slug = "yoga-wide-child",
            category = Category.YOGA,
            titleFa = "کودک گسترده",
            level = 2,
            durationSec = 60,
            instructionsFa = "مثل کودک، اما زانوها از هم باز. پیشانی روی زمین، بازوها جلو یا کنار بدن.",
            audioCueId = "cue-yoga-wide-child-start.mp3|cue-yoga-wide-child-mid.mp3|cue-yoga-wide-child-end.mp3",
            referenceImageUrl = embeddedCover("yga-10"),
            referenceImagePromptTemplate = "تصویر آموزشی از کودک گسترده با چهره‌ی مرجع، نمای جلو، پوشش ورزشی، بدون متن.",
            orderIndex = 10,
        ),
        WellnessMove(
            slug = "yoga-pigeon",
            category = Category.YOGA,
            titleFa = "کبوتر",
            level = 5,
            durationSec = 60,
            instructionsFa = "پای جلو خم با زانو پشت مچ دست جلو، پای عقب صاف به عقب. تنه عمودی، دست‌ها روی زمین.",
            audioCueId = "cue-yoga-pigeon-start.mp3|cue-yoga-pigeon-mid.mp3|cue-yoga-pigeon-end.mp3",
            referenceImageUrl = embeddedCover("yga-11"),
            referenceImagePromptTemplate = "تصویر آموزشی از کبوتر (Pigeon Pose) با چهره‌ی مرجع، نمای سه‌ربع، پوشش ورزشی، بدون متن.",
            orderIndex = 11,
            tags = listOf("بازکننده‌ی لگن"),
        ),
        WellnessMove(
            slug = "yoga-triangle",
            category = Category.YOGA,
            titleFa = "مثلث",
            level = 5,
            durationSec = 30,
            instructionsFa = "پاها باز، پای جلو رو به جلو، پای عقب ۹۰ درجه. دست جلو به ساق پای جلو، دست عقب بالا. نگاه به دست بالا.",
            audioCueId = "cue-yoga-triangle-start.mp3|cue-yoga-triangle-mid.mp3|cue-yoga-triangle-end.mp3",
            referenceImageUrl = embeddedCover("yga-12"),
            referenceImagePromptTemplate = "تصویر آموزشی از مثلث (Triangle Pose) با چهره‌ی مرجع، نمای جلو، پوشش ورزشی، بدون متن.",
            orderIndex = 12,
        ),
        WellnessMove(
            slug = "yoga-savasana",
            category = Category.YOGA,
            titleFa = "شاواسانا (جسد)",
            level = 1,
            durationSec = 180,
            instructionsFa = "به پشت دراز بکش، پاها کمی باز، دست‌ها کنار بدن با کف دست رو به بالا. چشم‌ها بسته. کاملاً رها کن.",
            audioCueId = "cue-yoga-savasana-start.mp3|cue-yoga-savasana-mid.mp3|cue-yoga-savasana-end.mp3",
            referenceImageUrl = embeddedCover("yga-13"),
            referenceImagePromptTemplate = "تصویر آموزشی از شاواسانا (Corpse Pose) با چهره‌ی مرجع، نمای بالا، پوشش ورزشی، بدون متن.",
            orderIndex = 13,
            tags = listOf("ریلکسیشن نهایی"),
        ),
        WellnessMove(
            slug = "yoga-half-boat",
            category = Category.YOGA,
            titleFa = "نیم‌قایق",
            level = 6,
            durationSec = 30,
            instructionsFa = "بنشین، زانوها خم با ساق موازی زمین. تنه کمی به عقب، دست‌ها جلو موازی زمین. V شکل.",
            audioCueId = "cue-yoga-half-boat-start.mp3|cue-yoga-half-boat-mid.mp3|cue-yoga-half-boat-end.mp3",
            referenceImageUrl = embeddedCover("yga-14"),
            referenceImagePromptTemplate = "تصویر آموزشی از نیم‌قایق (Half Boat) با چهره‌ی مرجع، نمای پهلو، پوشش ورزشی، بدون متن.",
            orderIndex = 14,
            tags = listOf("تقویت شکم"),
        ),
        WellnessMove(
            slug = "yoga-standing-forward-bend",
            category = Category.YOGA,
            titleFa = "خم‌شدن ایستاده",
            level = 2,
            durationSec = 45,
            instructionsFa = "بایست، از لگن خم شو، سر آویزان، دست‌ها کنار پا. زانوها کمی خم.",
            audioCueId = "cue-yoga-standing-forward-bend-start.mp3|cue-yoga-standing-forward-bend-mid.mp3|cue-yoga-standing-forward-bend-end.mp3",
            referenceImageUrl = embeddedCover("yga-15"),
            referenceImagePromptTemplate = "تصویر آموزشی از خم‌شدن ایستاده (Standing Forward Bend) با چهره‌ی مرجع، نمای پهلو، پوشش ورزشی، بدون متن.",
            orderIndex = 15,
            tags = listOf("کشش همسترینگ"),
        ),
    )

    // ---------------- ورزش عمومی/کششی (15) ----------------

    val exercise: List<WellnessMove> = listOf(
        WellnessMove(
            slug = "ex-neck-4way",
            category = Category.EXERCISE,
            titleFa = "کشش گردن ۴ جهت",
            level = 1,
            durationSec = 60,
            instructionsFa = "سر را آرام به راست، چپ، جلو، عقب خم کن. هر طرف ۱۵ ثانیه. اگر سرگیجه داشتی بنشین.",
            audioCueId = "cue-ex-neck.mp3",
            referenceImageUrl = embeddedCover("spo-12"),
            referenceImagePromptTemplate = "تصویر آموزشی از کشش گردن با چهره‌ی مرجع، نمای جلو، پوشش ورزشی، بدون متن.",
            orderIndex = 1,
        ),
        WellnessMove(
            slug = "ex-shoulder-cross",
            category = Category.EXERCISE,
            titleFa = "کشش شانه ضربدری",
            level = 1,
            durationSec = 30,
            instructionsFa = "دست راست را افقی روی سینه بیاور، دست چپ آرنج راست را به سمت سینه بکشد. ۱۵ ثانیه هر طرف.",
            audioCueId = "cue-ex-shoulder.mp3",
            referenceImageUrl = embeddedCover("spo-11"),
            referenceImagePromptTemplate = "تصویر آموزشی از کشش شانه ضربدری با چهره‌ی مرجع، نمای جلو، پوشش ورزشی، بدون متن.",
            orderIndex = 2,
        ),
        WellnessMove(
            slug = "ex-wrist-ankle",
            category = Category.EXERCISE,
            titleFa = "چرخش مچ دست و پا",
            level = 1,
            durationSec = 60,
            instructionsFa = "مچ دست و پا را به آرامی در هر دو جهت ۱۰ بار بچرخان.",
            audioCueId = "cue-ex-wrist-ankle.mp3",
            referenceImageUrl = embeddedCover("spo-07"),
            referenceImagePromptTemplate = "تصویر آموزشی از چرخش مچ با چهره‌ی مرجع، نمای سه‌ربع، پوشش ورزشی، بدون متن.",
            orderIndex = 3,
        ),
        WellnessMove(
            slug = "ex-squat",
            category = Category.EXERCISE,
            titleFa = "اسکوات آرام",
            level = 4,
            durationSec = 60,
            reps = 10,
            instructionsFa = "پاها به عرض شانه. لگن را عقب ببر مثل نشستن روی صندلی. زانوها از انگشتان پا جلوتر نرود. ۱۰ بار.",
            audioCueId = "cue-ex-squat.mp3",
            referenceImageUrl = embeddedCover("spo-01"),
            referenceImagePromptTemplate = "تصویر آموزشی از اسکوات با چهره‌ی مرجع، نمای پهلو، پوشش ورزشی، بدون متن.",
            orderIndex = 4,
        ),
        WellnessMove(
            slug = "ex-lunge",
            category = Category.EXERCISE,
            titleFa = "لانگز",
            level = 4,
            durationSec = 60,
            reps = 10,
            instructionsFa = "یک پا جلو با زانوی ۹۰ درجه، پای عقب نزدیک زمین. ۱۰ بار هر طرف.",
            audioCueId = "cue-ex-lunge.mp3",
            referenceImageUrl = embeddedCover("spo-05"),
            referenceImagePromptTemplate = "تصویر آموزشی از لانگز با چهره‌ی مرجع، نمای پهلو، پوشش ورزشی، بدون متن.",
            orderIndex = 5,
        ),
        WellnessMove(
            slug = "ex-plank",
            category = Category.EXERCISE,
            titleFa = "پلانک (روی آرنج)",
            level = 5,
            durationSec = 30,
            instructionsFa = "روی آرنج و انگشتان پا، بدن صاف. شکم سفت. ۳۰ ثانیه (مبتدی)، بعد ۴۵ یا ۶۰.",
            audioCueId = "cue-ex-plank.mp3",
            referenceImageUrl = embeddedCover("spo-06"),
            referenceImagePromptTemplate = "تصویر آموزشی از پلانک با چهره‌ی مرجع، نمای پهلو، پوشش ورزشی، بدون متن.",
            orderIndex = 6,
        ),
        WellnessMove(
            slug = "ex-crunch",
            category = Category.EXERCISE,
            titleFa = "کرانچ شکم ملایم",
            level = 4,
            durationSec = 60,
            reps = 10,
            instructionsFa = "به پشت، زانوها خم، دست‌ها پشت سر. فقط شانه‌ها را بلند کن. ۱۰ بار.",
            audioCueId = "cue-ex-crunch.mp3",
            referenceImageUrl = embeddedCover("spo-09"),
            referenceImagePromptTemplate = "تصویر آموزشی از کرانچ با چهره‌ی مرجع، نمای پهلو، پوشش ورزشی، بدون متن.",
            orderIndex = 7,
        ),
        WellnessMove(
            slug = "ex-hamstring",
            category = Category.EXERCISE,
            titleFa = "کشش همسترینگ نشسته",
            level = 2,
            durationSec = 60,
            instructionsFa = "بنشین، یک پا صاف، پای دیگر خم. به سمت پای صاف خم شو. ۳۰ ثانیه هر طرف.",
            audioCueId = "cue-ex-hamstring.mp3",
            referenceImageUrl = embeddedCover("spo-14"),
            referenceImagePromptTemplate = "تصویر آموزشی از کشش همسترینگ با چهره‌ی مرجع، نمای سه‌ربع، پوشش ورزشی، بدون متن.",
            orderIndex = 8,
        ),
        WellnessMove(
            slug = "ex-butterfly",
            category = Category.EXERCISE,
            titleFa = "حرکت پروانه",
            level = 1,
            durationSec = 45,
            instructionsFa = "بنشین، کف پاها به هم، زانوها باز. کمر صاف. ۴۵ ثانیه.",
            audioCueId = "cue-ex-butterfly.mp3",
            referenceImageUrl = embeddedCover("spo-15"),
            referenceImagePromptTemplate = "تصویر آموزشی از پروانه با چهره‌ی مرجع، نمای جلو، پوشش ورزشی، بدون متن.",
            orderIndex = 9,
        ),
        WellnessMove(
            slug = "ex-calf-raise",
            category = Category.EXERCISE,
            titleFa = "بالا-پایین پاشنه (Calf Raises)",
            level = 3,
            durationSec = 45,
            reps = 15,
            instructionsFa = "بایست، پاشنه‌ها بالا، ۲ ثانیه نگه‌دار، پایین. ۱۵ بار.",
            audioCueId = "cue-ex-calf.mp3",
            referenceImageUrl = embeddedCover("spo-02"),
            referenceImagePromptTemplate = "تصویر آموزشی از بالا-پایین پاشنه با چهره‌ی مرجع، نمای پهلو، پوشش ورزشی، بدون متن.",
            orderIndex = 10,
        ),
        WellnessMove(
            slug = "ex-trunk-rotation",
            category = Category.EXERCISE,
            titleFa = "چرخش تنه ایستاده",
            level = 2,
            durationSec = 45,
            instructionsFa = "بایست، دست‌ها جلوی سینه. آرام به راست و چپ بچرخ. ۱۵ ثانیه هر طرف.",
            audioCueId = "cue-ex-trunk.mp3",
            referenceImageUrl = embeddedCover("spo-08"),
            referenceImagePromptTemplate = "تصویر آموزشی از چرخش تنه با چهره‌ی مرجع، نمای جلو، پوشش ورزشی، بدون متن.",
            orderIndex = 11,
        ),
        WellnessMove(
            slug = "ex-wall-calf",
            category = Category.EXERCISE,
            titleFa = "کشش ساق پا به دیوار",
            level = 2,
            durationSec = 45,
            instructionsFa = "رو به دیوار، یک پا عقب با پاشنه روی زمین. به دیوار تکیه بده تا ساق کش بیاید. ۳۰ ثانیه هر طرف.",
            audioCueId = "cue-ex-wall-calf.mp3",
            referenceImageUrl = embeddedCover("spo-10"),
            referenceImagePromptTemplate = "تصویر آموزشی از کشش ساق به دیوار با چهره‌ی مرجع، نمای پهلو، پوشش ورزشی، بدون متن.",
            orderIndex = 12,
        ),
        WellnessMove(
            slug = "ex-superman",
            category = Category.EXERCISE,
            titleFa = "سوپرمن (تقویت کمر)",
            level = 5,
            durationSec = 45,
            reps = 8,
            instructionsFa = "روی شکم، دست و پا صاف. همزمان دست و پای مخالف بالا ببر. ۸ بار هر طرف.",
            audioCueId = "cue-ex-superman.mp3",
            referenceImageUrl = embeddedCover("spo-04"),
            referenceImagePromptTemplate = "تصویر آموزشی از سوپرمن با چهره‌ی مرجع، نمای پهلو، پوشش ورزشی، بدون متن.",
            orderIndex = 13,
        ),
        WellnessMove(
            slug = "ex-jumping-jack",
            category = Category.EXERCISE,
            titleFa = "جامپینگ جک ملایم (گرم‌کردن)",
            level = 4,
            durationSec = 60,
            reps = 15,
            instructionsFa = "بایست، پاها باز و دست‌ها بالا، بعد برگرد. آرام و کنترل‌شده. ۱۵ بار.",
            audioCueId = "cue-ex-jj.mp3",
            referenceImageUrl = embeddedCover("spo-03"),
            referenceImagePromptTemplate = "تصویر آموزشی از جامپینگ جک با چهره‌ی مرجع، نمای جلو، پوشش ورزشی، بدون متن.",
            orderIndex = 14,
            tags = listOf("گرم‌کردن"),
        ),
        WellnessMove(
            slug = "ex-wrist-forearm",
            category = Category.EXERCISE,
            titleFa = "کشش مچ و ساعد",
            level = 1,
            durationSec = 45,
            instructionsFa = "دست صاف جلو، کف دست بالا. با دست دیگر انگشتان را به سمت خودت بکش. ۲۰ ثانیه هر طرف.",
            audioCueId = "cue-ex-wrist-forearm.mp3",
            referenceImageUrl = embeddedCover("spo-13"),
            referenceImagePromptTemplate = "تصویر آموزشی از کشش مچ با چهره‌ی مرجع، نمای سه‌ربع، پوشش ورزشی، بدون متن.",
            orderIndex = 15,
        ),
    )

    // ---------------- تنفس (8) ----------------

    val breathing: List<WellnessMove> = listOf(
        WellnessMove(
            slug = "breath-diaphragm",
            category = Category.BREATHING,
            titleFa = "تنفس شکمی (Diaphragmatic)",
            level = 1,
            durationSec = 120,
            instructionsFa = "یک دست روی شکم، یک دست روی سینه. با دم شکم بالا بیاید (سینه تکان نخورد). ۱۰ نفس.",
            audioCueId = "cue-breath-diaphragm.mp3",
            referenceImageUrl = imageUrl("breathing/01-diaphragmatic.jpg"),
            referenceImagePromptTemplate = "تصویر آموزشی از تنفس شکمی با چهره‌ی مرجع، نمای جلو، پوشش ورزشی، بدون متن.",
            orderIndex = 1,
        ),
        WellnessMove(
            slug = "breath-4-7-8",
            category = Category.BREATHING,
            titleFa = "تنفس ۴-۷-۸ (آرام‌بخش)",
            level = 2,
            durationSec = 120,
            instructionsFa = "۴ ثانیه دم، ۷ ثانیه نگه، ۸ ثانیه بازدم. ۴ دور.",
            audioCueId = "cue-breath-478.mp3",
            referenceImageUrl = imageUrl("breathing/02-4-7-8-breath.jpg"),
            referenceImagePromptTemplate = "تصویر آموزشی از ۴-۷-۸ با چهره‌ی مرجع، نمای جلو، پوشش ورزشی، بدون متن.",
            orderIndex = 2,
            tags = listOf("خواب"),
        ),
        WellnessMove(
            slug = "breath-box",
            category = Category.BREATHING,
            titleFa = "تنفس جعبه‌ای (Box 4-4-4-4)",
            level = 2,
            durationSec = 180,
            instructionsFa = "۴ دم، ۴ نگه، ۴ بازدم، ۴ سکوت. ۵ دور.",
            audioCueId = "cue-breath-box.mp3",
            referenceImageUrl = imageUrl("breathing/03-box-breathing.jpg"),
            referenceImagePromptTemplate = "تصویر آموزشی از تنفس جعبه‌ای با چهره‌ی مرجع، نمای جلو، پوشش ورزشی، بدون متن.",
            orderIndex = 3,
            tags = listOf("تمرکز"),
        ),
        WellnessMove(
            slug = "breath-nadi",
            category = Category.BREATHING,
            titleFa = "تنفس بینی متناوب (Nadi Shodhana)",
            level = 4,
            durationSec = 180,
            instructionsFa = "شست سوراخ راست، انگشت حلقه سوراخ چپ. ۴ دم چپ، ۴ نگه، ۴ بازدم راست، ۴ دم راست... ۵ دور.",
            audioCueId = "cue-breath-nadi.mp3",
            referenceImageUrl = imageUrl("breathing/04-nadi-shodhana.jpg"),
            referenceImagePromptTemplate = "تصویر آموزشی از نادی شودهانا با چهره‌ی مرجع، نمای جلو، پوشش ورزشی، بدون متن.",
            orderIndex = 4,
        ),
        WellnessMove(
            slug = "breath-sigh",
            category = Category.BREATHING,
            titleFa = "آه‌کشیدن آرام‌بخش",
            level = 1,
            durationSec = 90,
            instructionsFa = "یک دم عمیق و یک آه بلند. تکرار تا آرامش.",
            audioCueId = "cue-breath-sigh.mp3",
            referenceImageUrl = imageUrl("breathing/05-sighing-breath.jpg"),
            referenceImagePromptTemplate = "تصویر آموزشی از آه‌کشیدن با چهره‌ی مرجع، نمای جلو، پوشش ورزشی، بدون متن.",
            orderIndex = 5,
        ),
        WellnessMove(
            slug = "breath-lion",
            category = Category.BREATHING,
            titleFa = "تنفس شیر (Lion's Breath)",
            level = 5,
            durationSec = 60,
            instructionsFa = "روی پاشنه، دهان باز، زبان بیرون، با صدای «ها» بازدم. ۵ بار.",
            audioCueId = "cue-breath-lion.mp3",
            referenceImageUrl = imageUrl("breathing/06-lions-breath.jpg"),
            referenceImagePromptTemplate = "تصویر آموزشی از تنفس شیر با چهره‌ی مرجع، نمای جلو، پوشش ورزشی، بدون متن.",
            orderIndex = 6,
            tags = listOf("رهاسازی تنش"),
        ),
        WellnessMove(
            slug = "breath-counting",
            category = Category.BREATHING,
            titleFa = "تنفس شمارشی قبل امتحان",
            level = 2,
            durationSec = 120,
            instructionsFa = "دم آرام تا ۴، نگه تا ۴، بازدم تا ۴. هر بار یکی بشمار. ۸ دور.",
            audioCueId = "cue-breath-counting.mp3",
            referenceImageUrl = imageUrl("breathing/07-counting-breath.jpg"),
            referenceImagePromptTemplate = "تصویر آموزشی از تنفس شمارشی با چهره‌ی مرجع، نمای جلو، پوشش ورزشی، بدون متن.",
            orderIndex = 7,
            tags = listOf("تمرکز", "امتحان"),
        ),
        WellnessMove(
            slug = "breath-bedtime",
            category = Category.BREATHING,
            titleFa = "آرام‌سازی قبل خواب",
            level = 1,
            durationSec = 300,
            instructionsFa = "به پشت یا پهلو. ۴ دم، ۶ بازدم. ۱۰ دور.",
            audioCueId = "cue-breath-bedtime.mp3",
            referenceImageUrl = imageUrl("breathing/08-bedtime-breath.jpg"),
            referenceImagePromptTemplate = "تصویر آموزشی از آرام‌سازی قبل خواب با چهره‌ی مرجع، نمای پهلو، پوشش ورزشی، بدون متن.",
            orderIndex = 8,
            tags = listOf("خواب"),
        ),
    )

    // ---------------- تکنیک‌های یادگیری (5) ----------------

    val learning: List<WellnessMove> = listOf(
        WellnessMove(
            slug = "learn-pomodoro",
            category = Category.LEARNING,
            titleFa = "تکنیک پومودورو (۲۵/۵)",
            level = 1,
            durationSec = 1500,
            instructionsFa = "۲۵ دقیقه مطالعه‌ی متمرکز، ۵ دقیقه استراحت. ۴ دور = ۲ ساعت کار. ۱۵-۲۰ دقیقه استراحت بلند.",
            audioCueId = "cue-learn-pomodoro.mp3",
            referenceImageUrl = imageUrl("learning/01-pomodoro.jpg"),
            referenceImagePromptTemplate = "تصویر آموزشی از تکنیک پومودورو با چهره‌ی مرجع، نمای جلو، پوشش ورزشی، بدون متن.",
            orderIndex = 1,
        ),
        WellnessMove(
            slug = "learn-spaced-repetition",
            category = Category.LEARNING,
            titleFa = "تکنیک تکرار فاصله‌دار",
            level = 2,
            durationSec = 600,
            instructionsFa = "فلش‌کارت‌ها را با فاصله‌ی ۱، ۳، ۷، ۱۴، ۳۰ روز مرور کن. اگر غلط: فردا؛ درست: فاصله × ۲.۵.",
            audioCueId = "cue-learn-spaced.mp3",
            referenceImageUrl = imageUrl("learning/02-spaced-repetition.jpg"),
            referenceImagePromptTemplate = "تصویر آموزشی از تکرار فاصله‌دار با چهره‌ی مرجع، نمای جلو، پوشش ورزشی، بدون متن.",
            orderIndex = 2,
        ),
        WellnessMove(
            slug = "learn-feynman",
            category = Category.LEARNING,
            titleFa = "روش فاینمن",
            level = 2,
            durationSec = 600,
            instructionsFa = "۱) موضوع را یاد بگیر. ۲) به زبان ساده به کودک ۱۰ ساله توضیح بده. ۳) شکاف‌ها را پیدا کن. ۴) دوباره بخوان و ساده‌تر کن.",
            audioCueId = "cue-learn-feynman.mp3",
            referenceImageUrl = imageUrl("learning/03-feynman.jpg"),
            referenceImagePromptTemplate = "تصویر آموزشی از روش فاینمن با چهره‌ی مرجع، نمای جلو، پوشش ورزشی، بدون متن.",
            orderIndex = 3,
        ),
        WellnessMove(
            slug = "learn-mind-map",
            category = Category.LEARNING,
            titleFa = "نقشه‌ی ذهنی (Mind Map)",
            level = 2,
            durationSec = 900,
            instructionsFa = "موضوع مرکزی در وسط کاغذ. شاخه‌های اصلی. زیرشاخه‌ها با کلیدواژه. رنگ و تصویر.",
            audioCueId = "cue-learn-mindmap.mp3",
            referenceImageUrl = imageUrl("learning/04-mind-map.jpg"),
            referenceImagePromptTemplate = "تصویر آموزشی از نقشه‌ی ذهنی با چهره‌ی مرجع، نمای سه‌ربع، پوشش ورزشی، بدون متن.",
            orderIndex = 4,
        ),
        WellnessMove(
            slug = "learn-active-recall",
            category = Category.LEARNING,
            titleFa = "فعال‌سازی حافظه (Active Recall)",
            level = 2,
            durationSec = 600,
            instructionsFa = "قبل از خواندن، از خودت بپرس: «چه می‌دانم؟». بعد بخوان. بعد دوباره بدون نگاه‌کردن بگو.",
            audioCueId = "cue-learn-recall.mp3",
            referenceImageUrl = imageUrl("learning/05-active-recall.jpg"),
            referenceImagePromptTemplate = "تصویر آموزشی از فعال‌سازی حافظه با چهره‌ی مرجع، نمای جلو، پوشش ورزشی، بدون متن.",
            orderIndex = 5,
        ),
    )

    /** همه‌ی ۴۳ حرکت. */
    val all: List<WellnessMove> = yoga + exercise + breathing + learning

    fun byCategory(category: Category): List<WellnessMove> = when (category) {
        Category.YOGA -> yoga
        Category.EXERCISE -> exercise
        Category.BREATHING -> breathing
        Category.LEARNING -> learning
    }

    fun bySlug(slug: String): WellnessMove? = all.firstOrNull { it.slug == slug }
}
