package com.hamyareman.ir.platform.core.designsystem

import androidx.compose.ui.graphics.Color

/**
 * پالت‌های تم اضافه (۱۴۰۴/۰۶) — هر تم دو نسخه‌ی روشن/تاریک دارد.
 * «Stitch» الهام‌گرفته از حال‌وهوای رنگی شخصیت‌های فضایی بازیگوش
 * (آبی الکتریکی + صورتی مرجانی + بنفش گرم، حال‌وهوای جزیره‌ای) است؛
 * اثر ترفیعی خاصی کپی نمی‌شود و ماسموت اپ اورجینال است.
 */

// ---------- Stitch (جزیره‌ای/فضایی) ----------
val StitchBlue = Color(0xFF2F7FD6)
val StitchOnBlue = Color(0xFFFFFFFF)
val StitchBlueContainer = Color(0xFFD6E8FF)
val StitchOnBlueContainer = Color(0xFF0B2B52)
val StitchPink = Color(0xFFF26FA7)
val StitchOnPink = Color(0xFF3E0A24)
val StitchPinkContainer = Color(0xFFFFD8E8)
val StitchOnPinkContainer = Color(0xFF45102B)
val StitchTeal = Color(0xFF27B5A8)
val StitchOnTeal = Color(0xFF00332E)
val StitchTealContainer = Color(0xFFC9F2ED)
val StitchOnTealContainer = Color(0xFF003832)
val StitchBg = Color(0xFFF3F9FF)
val StitchOnBg = Color(0xFF14212E)
val StitchSurface = Color(0xFFFAFDFF)
val StitchSurfaceVariant = Color(0xFFE1EBF4)
val StitchOnSurfaceVariant = Color(0xFF50616F)
val StitchOutline = Color(0xFFC3D2DE)
val StitchError = Color(0xFFBA1A1A)

val StitchBlueNight = Color(0xFF9FCBFF)
val StitchOnBlueNight = Color(0xFF00335E)
val StitchBlueNightContainer = Color(0xFF1B4C7E)
val StitchOnBlueNightContainer = Color(0xFFD6E8FF)
val StitchPinkNight = Color(0xFFFFB1D1)
val StitchOnPinkNight = Color(0xFF5E1136)
val StitchPinkNightContainer = Color(0xFF87294F)
val StitchOnPinkNightContainer = Color(0xFFFFD8E8)
val StitchTealNight = Color(0xFF86D6CC)
val StitchOnTealNight = Color(0xFF003733)
val StitchTealNightContainer = Color(0xFF1F4E49)
val StitchOnTealNightContainer = Color(0xFFC9F2ED)
val StitchNightBg = Color(0xFF0E141B)
val StitchNightOnBg = Color(0xFFDEE9F2)
val StitchNightSurface = Color(0xFF101821)
val StitchNightSurfaceVariant = Color(0xFF3C4A57)
val StitchNightOnSurfaceVariant = Color(0xFFBAC9D6)
val StitchNightOutline = Color(0xFF8494A2)
val StitchNightError = Color(0xFFFFB4AB)

// ---------- ماه/شب (بنفش آرام شبانه) ----------
val MoonViolet = Color(0xFF7C6BD9)
val MoonOnViolet = Color(0xFFFFFFFF)
val MoonVioletContainer = Color(0xFFE7DEFF)
val MoonOnVioletContainer = Color(0xFF241756)
val MoonGold = Color(0xFFE8B84B)
val MoonOnGold = Color(0xFF3F2D04)
val MoonGoldContainer = Color(0xFFFFEFC2)
val MoonOnGoldContainer = Color(0xFF3F2D04)
val MoonRose = Color(0xFFC97BA8)
val MoonOnRose = Color(0xFF3B1030)
val MoonRoseContainer = Color(0xFFFFD9EE)
val MoonOnRoseContainer = Color(0xFF3B1030)
val MoonBg = Color(0xFFF7F5FF)
val MoonOnBg = Color(0xFF1C1A2A)
val MoonSurface = Color(0xFFFCFAFF)
val MoonSurfaceVariant = Color(0xFFE8E4F5)
val MoonOnSurfaceVariant = Color(0xFF5D5975)
val MoonOutline = Color(0xFFCCC8E0)
val MoonError = Color(0xFFBA1A1A)

val MoonVioletNight = Color(0xFFC9BFFF)
val MoonOnVioletNight = Color(0xFF2E2160)
val MoonVioletNightContainer = Color(0xFF45377B)
val MoonOnVioletNightContainer = Color(0xFFE7DEFF)
val MoonGoldNight = Color(0xFFFFDF8F)
val MoonOnGoldNight = Color(0xFF3F2D04)
val MoonGoldNightContainer = Color(0xFF5B4516)
val MoonOnGoldNightContainer = Color(0xFFFFEFC2)
val MoonRoseNight = Color(0xFFF0A9CF)
val MoonOnRoseNight = Color(0xFF551D41)
val MoonRoseNightContainer = Color(0xFF703257)
val MoonOnRoseNightContainer = Color(0xFFFFD9EE)
val MoonNightBg = Color(0xFF131120)
val MoonNightOnBg = Color(0xFFE6E1F5)
val MoonNightSurface = Color(0xFF171425)
val MoonNightSurfaceVariant = Color(0xFF44415A)
val MoonNightOnSurfaceVariant = Color(0xFFC7C2DC)
val MoonNightOutline = Color(0xFF918FA8)
val MoonNightError = Color(0xFFFFB4AB)

// ---------- نعنایی (سبز تازه) ----------
val MintGreen = Color(0xFF2FA37A)
val MintOnGreen = Color(0xFFFFFFFF)
val MintGreenContainer = Color(0xFFCBF3E3)
val MintOnGreenContainer = Color(0xFF04382A)
val MintLime = Color(0xFF8FBF3C)
val MintOnLime = Color(0xFF243300)
val MintLimeContainer = Color(0xFFE5F5C0)
val MintOnLimeContainer = Color(0xFF243300)
val MintSky = Color(0xFF4FA8D9)
val MintOnSky = Color(0xFF002F42)
val MintSkyContainer = Color(0xFFCBE7F7)
val MintOnSkyContainer = Color(0xFF04354A)
val MintBg = Color(0xFFF4FBF7)
val MintOnBg = Color(0xFF16211D)
val MintSurface = Color(0xFFFAFEFC)
val MintSurfaceVariant = Color(0xFFDDEEE6)
val MintOnSurfaceVariant = Color(0xFF4C635A)
val MintOutline = Color(0xFFC2D8CE)
val MintError = Color(0xFFBA1A1A)

val MintGreenNight = Color(0xFF90D8BC)
val MintOnGreenNight = Color(0xFF003828)
val MintGreenNightContainer = Color(0xFF15503C)
val MintOnGreenNightContainer = Color(0xFFCBF3E3)
val MintLimeNight = Color(0xFFBCE35D)
val MintOnLimeNight = Color(0xFF243300)
val MintLimeNightContainer = Color(0xFF3E4D11)
val MintOnLimeNightContainer = Color(0xFFE5F5C0)
val MintSkyNight = Color(0xFF9ACDF0)
val MintOnSkyNight = Color(0xFF00344A)
val MintSkyNightContainer = Color(0xFF1F4B63)
val MintOnSkyNightContainer = Color(0xFFCBE7F7)
val MintNightBg = Color(0xFF0F1512)
val MintNightOnBg = Color(0xFFDDEDE5)
val MintNightSurface = Color(0xFF121A16)
val MintNightSurfaceVariant = Color(0xFF3A4942)
val MintNightOnSurfaceVariant = Color(0xFFB6CCC2)
val MintNightOutline = Color(0xFF82968C)
val MintNightError = Color(0xFFFFB4AB)
